export const ACTION_TYPE = {
  ADD_USER: "ADD_USER",
  UPDATE_TIME: "UPDATE_TIME",
  ADD_FOCUS: "ADD_FOCUS",
  EDIT_FOCUS: "EDIT_FOCUS",
  COMPLETE_FOCUS: "COMPLETE_FOCUS",
  CLEAR_FOCUS: "CLEAR_FOCUS",
};
